import KittyCats.Category
import KittyCats.Functor
import KittyCats.NatTrans
import KittyCats.Morphism
import KittyCats.Product
import KittyCats.Limits
import KittyCats.Cartesian
import KittyCats.Closed
import KittyCats.Monoidal
import KittyCats.Adjunction
import KittyCats.Monad
import KittyCats.Dual
import KittyCats.Equiv
import KittyCats.Instances
import KittyCats.Yoneda
import KittyCats.Thm
