import KittyCats.Category
import KittyCats.Functor
import KittyCats.NatTrans
import KittyCats.Morphism
import KittyCats.Product
import KittyCats.Limits
import KittyCats.Cartesian
import KittyCats.Closed
import KittyCats.Monoidal
import KittyCats.Adjunction
import KittyCats.Instances
import KittyCats.Thm
